implement social login functionality
andela/helios-ah-frontend pull request #27
Opened 2019-01-28 19:54 UTC by andrewinsoul

#### What does this PR do?
This PR implements the social login functionality on the client side.

#### Description of task completed
Implement social login feature for Facebook and Google

#### How should this be manually tested?
- Run npm install
- npm start
- navigate to the login route

#### Any Background context you want to provide?
- #### N/A

#### What are the relevant Pivotal Tracker stories?
[161779741](https://www.pivotaltracker.com/story/show/161779741)

#### Screenshots(if applicable)

![image](https://user-images.githubusercontent.com/25207671/51551621-1ab84d80-1e6f-11e9-8951-8acd41f39b0b.png)

2019-01-29 07:00 UTC, kingisaac95 requested changes

2019-01-29 07:00 UTC, kingisaac95 commented on src/actions/socialLoginAction.js
> +    if (platform === 'social_ggl' && res.data.token) {
Re-write this using a switch statement, or have all platform checks wrapped in a single if statement that checks for a token in the response body.

2019-01-29 07:00 UTC, kingisaac95 commented on src/components/AuthVerify.jsx
> +    if (window.location.pathname.includes('social_ggl')) {
Have a method to run this check, and use the react-router object instead of `window.location`

2019-01-29 07:00 UTC, kingisaac95 commented on src/components/LoginForm.jsx
> +  window.location.href = url;
Use react-router push method

2019-01-29 07:00 UTC, kingisaac95 commented on src/components/LoginForm.jsx
> +              onClick={() => openLink(`${baseUrl}/auth/social_fb`)}
This will cause over-rendering. Abstract it as a function and give it parameters.

2019-01-29 07:00 UTC, kingisaac95 commented on src/routes.jsx
> +const socialLoginRe = /^\/api\/v1\/auth\/social_(ggl|tw|fb)/;
We don't need this @andrewinsoul. React router has a way of doing this already

2019-01-29 07:00 UTC, kingisaac95 commented on src/routes.jsx
> +      <Route path={socialLoginRe} component={AuthVerify} />
Change this line to
`<Route path="/api/v1/auth/social_(ggl|tw|fb)/" component={AuthVerify} />`

2019-01-29 07:00 UTC, kingisaac95 commented on src/utilities/apiRequests.js
>    ? 'https://helios-ah-backend-staging.herokuapp.com/api/v1'
Why are we hard coding this url?

2019-01-29 07:00 UTC, kingisaac95 commented on src/utilities/apiRequests.js
> +  : 'http://localhost:4001/api/v1';
Why are we also hard coding this url?

2019-01-29 14:02 UTC, nwashangai commented on src/actions/socialLoginAction.js
> +} from '../actionTypes/index';
@andrewinsoul you can take away the `index` and just leave it as
 `import {
  FACEBOOK_LOGIN,
  GOOGLE_LOGIN,
  TWITTER_LOGIN,
  LOGIN_FAIL
} from '../actionTypes';`

2019-01-31 11:11 UTC, kingisaac95 approved these changes

2019-01-31 11:11 UTC, merged